{{- if .Values.cron.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-cron
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    role: cron
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
      role: cron
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Values.name }}
        role: cron
    spec:
      containers:
      - name: app
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONSUL_HTTP_ADDR
          value: $(HOST_IP):8500
        - name: SERVICE_ROLE
          value: cron
        - name: SERVICE_NAME
          value: {{ .Values.env }}-{{ .Values.namespace }}-{{ .Values.name }}-cron
        {{- with .Values.cron.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: family.{{ .Values.namespace }}
        - configMapRef:
            name: app.{{ .Values.name }}
        - secretRef:
            name: app.{{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - '! (supervisorctl status all | grep -qs FATAL)'
          failureThreshold: {{ .Values.cron.livenessProbe.failureThreshold | default 3 }}
          initialDelaySeconds: {{ .Values.cron.livenessProbe.initialDelaySeconds | default 10 }}
          periodSeconds: {{ .Values.cron.livenessProbe.periodSeconds | default 10 }}
          successThreshold: {{ .Values.cron.livenessProbe.successThreshold | default 1 }}
          timeoutSeconds: {{ .Values.cron.livenessProbe.timeoutSeconds | default 3 }}
        resources:
          {{- toYaml .Values.cron.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /app/storage/logs/json
          name: logs-app
          subPathExpr: $(NAMESPACE_NAME)_$(POD_NAME)
      imagePullSecrets:
      - name: docker-auth
      terminationGracePeriodSeconds: {{ .Values.cron.terminationGracePeriodSeconds | default 30 }}
      volumes:
      - hostPath:
          path: {{ .Values.logs.app }}
          type: ""
        name: logs-app
{{- end -}}
