{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    role: web
spec:
  replicas: {{ .Values.web.replicaCount | default 2 }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
      role: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Values.name }}
        role: web
    spec:
      containers:
      - name: app
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONSUL_HTTP_ADDR
          value: $(HOST_IP):8500
        - name: SERVICE_ROLE
          value: web
        - name: SERVICE_NAME
          value: {{ .Values.env }}-{{ .Values.namespace }}-{{ .Values.name }}
        {{- with .Values.web.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: family.{{ .Values.namespace }}
        - configMapRef:
            name: app.{{ .Values.name }}
        - secretRef:
            name: app.{{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-main
          containerPort: {{ .Values.web.appPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.web.statusPath }}
            port: {{ .Values.web.appPort }}
            scheme: HTTP
          failureThreshold: {{ .Values.web.livenessProbe.failureThreshold | default 60 }}
          initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds | default 10 }}
          periodSeconds: {{ .Values.web.livenessProbe.periodSeconds | default 10 }}
          successThreshold: {{ .Values.web.livenessProbe.successThreshold | default 1 }}
          timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds | default 3 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.web.statusPath }}
            port: {{ .Values.web.appPort }}
            scheme: HTTP
          failureThreshold: {{ .Values.web.readinessProbe.failureThreshold | default 3 }}
          initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds | default 10 }}
          periodSeconds: {{ .Values.web.readinessProbe.periodSeconds | default 5 }}
          successThreshold: {{ .Values.web.readinessProbe.successThreshold | default 2 }}
          timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds | default 3 }}
        resources:
          limits:
            cpu: {{ .Values.web.resources.limits_cpu | default "100m" }}
            memory: {{ .Values.web.resources.limits_memory | default "128Mi" }}
          requests:
            cpu: {{ .Values.web.resources.requests_cpu | default "200m" }}
            memory: {{ .Values.web.resources.requests_memory | default "256Mi" }}
        volumeMounts:
        - mountPath: /app/storage/logs/json
          name: logs-app
          subPathExpr: $(NAMESPACE_NAME)_$(POD_NAME)
        - mountPath: /var/log/nginx
          name: logs-nginx
          subPathExpr: $(NAMESPACE_NAME)_$(POD_NAME)
      imagePullSecrets:
      - name: docker-auth
      terminationGracePeriodSeconds: {{ .Values.web.terminationGracePeriodSeconds | default 30 }}
      volumes:
      - hostPath:
          path: {{ .Values.logs.app }}
          type: ""
        name: logs-app
      - hostPath:
          path: {{ .Values.logs.nginx }}
          type: ""
        name: logs-nginx
{{- end -}}
