{{- if and .Values.worker.enabled (gt (.Values.worker.replicaCount | int) 1) -}}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  labels:
    app: {{ .Values.name }}
    role: worker
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      role: worker
{{- end -}}
