{{- if .Values.web.enabled -}}
kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Values.name }}
    role: web
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.web.servicePort }}
    protocol: TCP
    targetPort: http-main
  selector:
    app: {{ .Values.name }}
    role: web
  type: NodePort
{{- end -}}
