{{- if .Values.web.enabled -}}
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  labels:
    app: {{ .Values.name }}
    role: web
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  {{- if .Values.serviceMesh.mesh }}
  - mesh
  {{- end }}
  - {{ .Values.serviceMesh.gateway }}
  hosts:
  - {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local
  - {{ .Values.serviceMesh.hosts }}
  http:
  - route:
    - destination:
        host: {{ .Values.name }}.{{ .Values.namespace }}.svc.cluster.local
{{- end -}}
